Global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'amd-validation-production'
    static_configs:
      - targets: ['localhost:9090']
    file_sd_configs:
      - files:
          - 'data/vault/metrics.txt'

